### ISSUE TITLE
Minor issue, .DS_Store file

### ISSUE THREAD

**Issue by data-harmonization** [jordanbtucker/odrive-crypt#3]
Hi Jordan, great thing that you created this application!

When testing the application, I downloaded my encrypted files. When trying to decrypt, my Mac already had created a .DS_Store file in the encrypted folder. When removing this file, I was able to decrypt my encrypted files again.

Here is the error I got when the .DS_Store file was still in the encrypted folder.

$ odrive-crypt -i _Test_Encrypted -o _Test
Passphrase: 
Error: Unsupported state : _Test_Encrypted/.DS_Store
readline.js:982
            throw err;
            ^
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at decryptFile (/Users/pstapersma/.npm-packages/lib/node_modules/odrive-crypt/src/bin.js:158:23)
    at decryptDirectoryItem (/Users/pstapersma/.npm-packages/lib/node_modules/odrive-crypt/src/bin.js:270:3)
    at decryptNextItem (/Users/pstapersma/.npm-packages/lib/node_modules/odrive-crypt/src/bin.js:235:3)
    at decryptDirectoryItems (/Users/pstapersma/.npm-packages/lib/node_modules/odrive-crypt/src/bin.js:249:3)
    at decrypt (/Users/pstapersma/.npm-packages/lib/node_modules/odrive-crypt/src/bin.js:133:3)
    at err (/Users/pstapersma/.npm-packages/lib/node_modules/odrive-crypt/src/bin.js:19:4)
    at read (/Users/pstapersma/.npm-packages/lib/node_modules/odrive-crypt/src/bin.js:118:5)
    at Interface.onLine (/Users/pstapersma/.npm-packages/lib/node_modules/odrive-crypt/node_modules/read/lib/read.js:111:5)

**Comment by jordanbtucker** [comment]
Thanks for reporting this.

Fixed in v0.0.5.
